---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: app
spec: {}
status: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
automountServiceAccountToken: false
