---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2
  namespace: app
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: v2.0
  template:
    metadata:
      labels:
        app: web
        version: v2.0
    spec:
      serviceAccountName: app-sa
      containers:
      - name: web
        image:  rocksathish/web:bgv2
