apiVersion: v1
kind: Service
metadata:
  name: bg
  namespace: app
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
    version: v1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1.0
  template:
    metadata:
      labels:
        app: web
        version: v1.0
    spec:
      serviceAccountName: app-sa
      containers:
      - image: rocksathish/web:bgv1
        imagePullPolicy: IfNotPresent
        name: web
        resources: {}
      restartPolicy: Always
