apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: app
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webv1
  namespace: app
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: v1.0.0
  template:
    metadata:
      labels:
        app: web
        version: v1.0.0
    spec:
      serviceAccountName: app-sa
      containers:
      - name: web
        image:  rocksathish/web:canaryv1.1
