apiVersion: apps/v1
kind: Deployment
metadata:
  name: webv2
  labels:
    app: web
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: v2.0.0
  template:
    metadata:
      labels:
        app: web
        version: v2.0.0
    spec:
      serviceAccountName: app-sa
      containers:
      - name: web
        image: rocksathish/web:canaryv3
